jobs:
  build:
    runs-on: windows-latest
    env:
      NUITKA_USE_WINLIBS: "yes"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Cache Nuitka MinGW
        uses: actions/cache@v4
        with:
          path: C:\Users\runneradmin\AppData\Local\Nuitka\Nuitka\Cache\downloads\gcc
          key: ${{ runner.os }}-nuitka-gcc

      - name: Install dependencies
        shell: pwsh
        run: |
          pip install --upgrade pip
          if (Test-Path requirements.txt) { pip install -r requirements.txt }
          pip install nuitka

      - name: Build with Nuitka (Onefile EXE)
        shell: cmd
        run: |
          python -m nuitka ^
            --standalone ^
            --onefile ^
            --mingw64 ^
            --lto=no ^
            --output-dir=build ^
            main.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nuitka-exe
          path: build/
