name: Build with Nuitka

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: windows-latest  # 用 Windows Runner 才能打包成 EXE

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      # 缓存 pip，加速依赖安装
      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~\AppData\Local\pip\Cache
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          pip install --upgrade pip
          if exist requirements.txt (pip install -r requirements.txt)
          pip install nuitka

      - name: Build with Nuitka (Onefile EXE)
        run: |
          python -m nuitka ^
            --standalone ^
            --onefile ^
            --mingw64 ^
            --lto=no ^
            --output-dir=build ^
            main.py

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nuitka-exe
          path: build/
