name: Build with Nuitka

on:
  push:
    branches: [ "main" ]  # 触发分支
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest  # 或 windows-latest / macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Nuitka
        run: pip install nuitka

      - name: Build with Nuitka
        run: |
      - name: Build with Nuitka
        run: |
          python -m nuitka --standalone --onefile --follow-imports \
            --output-dir=build main.py


      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: nuitka-build
          path: build/
